"""Shared AgentBox application foundations."""

from agentbox_core.version import __version__
from agentbox_core.waw import (
    AgentType,
    AgentWorkspaceSession,
    GenerationCounter,
    ReconciliationState,
    StopResult,
    WAWDomainError,
    WorkspaceState,
    WorkspaceStopOperation,
    WriterLease,
    WriterLeaseSlot,
    managed_marker,
    managed_session_name,
    new_attachment_id,
    validate_attachment_id,
    validate_binding_digest,
    validate_positive_u64,
    validate_project_id,
    validate_runtime_host_installation_id,
    validate_stop_operation_id,
    validate_workspace_id,
    workspace_id,
)
from agentbox_core.waw_tickets import (
    ActiveAttachment,
    AttachmentAuthority,
    AttachmentTuple,
    AuthenticatedAttachmentContext,
    IssuedAttachmentTicket,
    TicketAuthorityError,
    TicketErrorCode,
)

__all__ = [
    "AgentType",
    "AgentWorkspaceSession",
    "ActiveAttachment",
    "AuthenticatedAttachmentContext",
    "AttachmentAuthority",
    "AttachmentTuple",
    "GenerationCounter",
    "IssuedAttachmentTicket",
    "ReconciliationState",
    "StopResult",
    "TicketAuthorityError",
    "TicketErrorCode",
    "WAWDomainError",
    "WorkspaceState",
    "WorkspaceStopOperation",
    "WriterLease",
    "WriterLeaseSlot",
    "managed_marker",
    "managed_session_name",
    "new_attachment_id",
    "validate_attachment_id",
    "validate_binding_digest",
    "validate_positive_u64",
    "validate_project_id",
    "validate_runtime_host_installation_id",
    "validate_stop_operation_id",
    "validate_workspace_id",
    "workspace_id",
    "__version__",
]
