#ifndef AGENTBOX_WAW_PROTOCOL_H
#define AGENTBOX_WAW_PROTOCOL_H

#include <stdint.h>

#define AGENTBOX_WAW_NATIVE_ABI_VERSION UINT32_C(1)
#define AGENTBOX_WAW_WORKSPACE_HASH_BYTES UINT32_C(64)
#define AGENTBOX_WAW_PROFILE_DIGEST_BYTES UINT32_C(64)

/* Fixed inherited descriptor numbers.  These are local process ABI values,
 * never browser/API fields. */
#define AGENTBOX_WAW_BOOTSTRAP_CONTROL_FD 3
#define AGENTBOX_WAW_BRIDGE_READY_FD 3
#define AGENTBOX_WAW_BRIDGE_CONFIG_FD 9
#define AGENTBOX_WAW_BRIDGE_PROJECT_FD 10
#define AGENTBOX_WAW_BRIDGE_HOME_FD 11
#define AGENTBOX_WAW_BRIDGE_TEMP_FD 12
#define AGENTBOX_WAW_BRIDGE_VENDOR_EXECUTABLE_FD 13
#define AGENTBOX_WAW_BRIDGE_POLICY_FD 14
#define AGENTBOX_WAW_BRIDGE_WBR_FD 15

#define AGENTBOX_WAW_ATTACH_TMUX_EXECUTABLE_FD 3
#define AGENTBOX_WAW_LAUNCHER_CGROUP_FD 3
#define AGENTBOX_WAW_LAUNCHER_TMUX_EXECUTABLE_FD 4
#define AGENTBOX_WAW_LAUNCHER_TMUX_CONFIG_FD 5
#define AGENTBOX_WAW_LAUNCHER_READY_FD 6
#define AGENTBOX_WAW_ATTACH_SOCKET_DIRECTORY_FD 4
#define AGENTBOX_WAW_ATTACH_CONFIG_FD 5
#define AGENTBOX_WAW_ATTACH_READY_FD 6

#define AGENTBOX_WAW_RELAY_BUFFER_BYTES UINT32_C(65536)
#define AGENTBOX_WAW_NATIVE_MAX_OPEN_FDS UINT32_C(64)
#define AGENTBOX_WAW_NATIVE_VERSION "1"
#define AGENTBOX_WAW_INNER_UID UINT32_C(1000)
#define AGENTBOX_WAW_INNER_GID UINT32_C(1000)
#define AGENTBOX_WAW_RUN_ROOT "/run/agentbox-waw"
#define AGENTBOX_WAW_STATE_ROOT "/var/lib/agentbox-waw"

/* Native readiness is one complete network-order byte record.  Bootstrap uses
 * the original launch connection; attach uses its dedicated fixed FD. */
#define AGENTBOX_WAW_READY_MAGIC "AWR1"
#define AGENTBOX_WAW_READY_VERSION UINT8_C(1)
#define AGENTBOX_WAW_READY_STATUS_RUNNING UINT8_C(1)
#define AGENTBOX_WAW_READY_FRAME_BYTES UINT32_C(8)
#define AGENTBOX_WAW_READY_DEADLINE_MS UINT32_C(1000)
#define AGENTBOX_WAW_READY_OFFSET_MAGIC UINT32_C(0)
#define AGENTBOX_WAW_READY_OFFSET_VERSION UINT32_C(4)
#define AGENTBOX_WAW_READY_OFFSET_STATUS UINT32_C(5)
#define AGENTBOX_WAW_READY_OFFSET_RESERVED UINT32_C(6)
#define AGENTBOX_WAW_READY_RESERVED_BYTES UINT32_C(2)

/* Canonical launch record identity. The JSON schema is closed. */
#define AGENTBOX_WAW_LAUNCH_SCHEMA "agentbox-waw-launch-v1"
#define AGENTBOX_WAW_LAUNCH_TYPE "interactive"
#define AGENTBOX_WAW_LAUNCH_MAX_BYTES UINT32_C(2048)
#define AGENTBOX_WAW_LAUNCH_FIELD_AGENT "agent"
#define AGENTBOX_WAW_LAUNCH_FIELD_FD_ROLE_BITMAP "fd_role_bitmap"
#define AGENTBOX_WAW_LAUNCH_FIELD_GENERATION "generation"
#define AGENTBOX_WAW_LAUNCH_FIELD_INITIAL_GEOMETRY "initial_geometry"
#define AGENTBOX_WAW_LAUNCH_FIELD_PROFILE_DIGEST "profile_digest"
#define AGENTBOX_WAW_LAUNCH_FIELD_RUNTIME_GID "runtime_gid"
#define AGENTBOX_WAW_LAUNCH_FIELD_RUNTIME_UID "runtime_uid"
#define AGENTBOX_WAW_LAUNCH_FIELD_SCHEMA "schema"
#define AGENTBOX_WAW_LAUNCH_FIELD_TYPE "type"
#define AGENTBOX_WAW_LAUNCH_FIELD_WORKSPACE_HASH "workspace_hash"
#define AGENTBOX_WAW_LAUNCH_FIELD_COLUMNS "columns"
#define AGENTBOX_WAW_LAUNCH_FIELD_ROWS "rows"

/* SCM_RIGHTS order. Every launch carries exactly these seven descriptors.
 * PROJECT is an O_PATH directory. HOME/TEMP/POLICY are directories. BRIDGE and
 * VENDOR are executable regular files. WBR is a connected AF_UNIX
 * SOCK_SEQPACKET endpoint. */
enum agentbox_waw_launch_fd_role {
    AGENTBOX_WAW_FD_PROJECT_DIRECTORY = 0,
    AGENTBOX_WAW_FD_SELECTED_HOME_DIRECTORY = 1,
    AGENTBOX_WAW_FD_TEMP_DIRECTORY = 2,
    AGENTBOX_WAW_FD_BRIDGE_EXECUTABLE = 3,
    AGENTBOX_WAW_FD_VENDOR_EXECUTABLE = 4,
    AGENTBOX_WAW_FD_POLICY_DIRECTORY = 5,
    AGENTBOX_WAW_FD_WBR_ENDPOINT = 6,
    AGENTBOX_WAW_FD_COUNT = 7
};

#define AGENTBOX_WAW_FD_ROLE_BIT(role) (UINT32_C(1) << (role))
#define AGENTBOX_WAW_FD_ROLE_BITMAP UINT32_C(0x7f)

/* WBR v1 is always one complete 64-byte network-order record. */
#define AGENTBOX_WBR_MAGIC "WBR1"
#define AGENTBOX_WBR_VERSION UINT8_C(1)
#define AGENTBOX_WBR_MESSAGE_RESIZE UINT8_C(1)
#define AGENTBOX_WBR_MESSAGE_ACK UINT8_C(2)
#define AGENTBOX_WBR_FLAGS UINT16_C(0)
#define AGENTBOX_WBR_RESIZE_MARKER UINT8_C(0)
#define AGENTBOX_WBR_ACK_MARKER UINT8_C(1)
#define AGENTBOX_WBR_FRAME_BYTES UINT32_C(64)
#define AGENTBOX_WBR_ACK_DEADLINE_MS UINT32_C(1000)

#define AGENTBOX_WBR_OFFSET_MAGIC UINT32_C(0)
#define AGENTBOX_WBR_OFFSET_VERSION UINT32_C(4)
#define AGENTBOX_WBR_OFFSET_MESSAGE_TYPE UINT32_C(5)
#define AGENTBOX_WBR_OFFSET_FLAGS UINT32_C(6)
#define AGENTBOX_WBR_OFFSET_SEQUENCE UINT32_C(8)
#define AGENTBOX_WBR_OFFSET_GENERATION UINT32_C(16)
#define AGENTBOX_WBR_OFFSET_COLUMNS UINT32_C(24)
#define AGENTBOX_WBR_OFFSET_ROWS UINT32_C(26)
#define AGENTBOX_WBR_OFFSET_REQUEST_OR_ACK UINT32_C(28)
#define AGENTBOX_WBR_OFFSET_RESERVED UINT32_C(29)
#define AGENTBOX_WBR_RESERVED_BYTES UINT32_C(35)

#define AGENTBOX_WBR_MIN_COLUMNS UINT16_C(8)
#define AGENTBOX_WBR_MAX_COLUMNS UINT16_C(240)
#define AGENTBOX_WBR_MIN_ROWS UINT16_C(1)
#define AGENTBOX_WBR_MAX_ROWS UINT16_C(200)

#endif /* AGENTBOX_WAW_PROTOCOL_H */
